export const atwTargets = [
  { target: 1, description: "1" },
  { target: 2, description: "2" },
  { target: 3, description: "3" },
  { target: 4, description: "4" },
  { target: 5, description: "5" },
  { target: 6, description: "6" },
  { target: 7, description: "7" },
  { target: 8, description: "8" },
  { target: 9, description: "9" },
  { target: 10, description: "10" },
  { target: 11, description: "11" },
  { target: 12, description: "12" },
  { target: 13, description: "13" },
  { target: 14, description: "14" },
  { target: 15, description: "15" },
  { target: 16, description: "16" },
  { target: 17, description: "17" },
  { target: 18, description: "18" },
  { target: 19, description: "19" },
  { target: 20, description: "20" },
  { target: 50, description: "Bull" },
];
