export const doubleTargets = [
  { target: 2, description: "Double 1" },
  { target: 4, description: "Double 2" },
  { target: 6, description: "Double 3" },
  { target: 8, description: "Double 4" },
  { target: 10, description: "Double 5" },
  { target: 12, description: "Double 6" },
  { target: 14, description: "Double 7" },
  { target: 16, description: "Double 8" },
  { target: 18, description: "Double 9" },
  { target: 20, description: "Double 10" },
  { target: 22, description: "Double 11" },
  { target: 24, description: "Double 12" },
  { target: 26, description: "Double 13" },
  { target: 28, description: "Double 14" },
  { target: 30, description: "Double 15" },
  { target: 32, description: "Double 16" },
  { target: 34, description: "Double 17" },
  { target: 36, description: "Double 18" },
  { target: 38, description: "Double 19" },
  { target: 40, description: "Double 20" },
  { target: 50, description: "Bull" },
];
