export const bobsTargets = [
  { target: 2, description: "Double 1" },
  { target: 4, description: "Double 2" },
  { target: 6, description: "Double 3" },
  { target: 8, description: "Double 4" },
  { target: 10, description: "Double 5" },
  { target: 12, description: "Double 6" },
  { target: 14, description: "Double 7" },
  { target: 16, description: "Double 8" },
  { target: 18, description: "Double 9" },
  { target: 20, description: "Double 10" },
  { target: 22, description: "Double 11" },
  { target: 24, description: "Double 12" },
  { target: 26, description: "Double 13" },
  { target: 28, description: "Double 14" },
  { target: 30, description: "Double 15" },
  { target: 32, description: "Double 16" },
  { target: 34, description: "Double 17" },
  { target: 36, description: "Double 18" },
  { target: 38, description: "Double 19" },
  { target: 40, description: "Double 20" },
  { target: 50, description: "Bull" },
];

export const atwTargets = [
  { target: 1, description: "Throw 1" },
  { target: 2, description: "Throw 2" },
  { target: 3, description: "Throw 3" },
  { target: 4, description: "Throw 4" },
  { target: 5, description: "Throw 5" },
  { target: 6, description: "Throw 6" },
  { target: 7, description: "Throw 7" },
  { target: 8, description: "Throw 8" },
  { target: 9, description: "Throw 9" },
  { target: 10, description: "Throw 10" },
  { target: 11, description: "Throw 11" },
  { target: 12, description: "Throw 12" },
  { target: 13, description: "Throw 13" },
  { target: 14, description: "Throw 14" },
  { target: 15, description: "Throw 15" },
  { target: 16, description: "Throw 16" },
  { target: 17, description: "Throw 17" },
  { target: 18, description: "Throw 18" },
  { target: 19, description: "Throw 19" },
  { target: 20, description: "Throw 20" },
  { target: 21, description: "Throw Bull" },
];
